import { Footer, Header } from "../components";

const groups = [
  { id:"ultrassonografia", code:"01 · Imagem em tempo real", title:"Ultrassonografia", text:"Exames em modo B, 3D e 4D, Doppler colorido, Power Doppler e Doppler espectral.", image:"exame-ultrassom.jpg", imageAlt:"Imagem de exame de ultrassonografia", label:"Exames realizados", items:["US pélvica transvaginal","US abdome inferior feminino","US controle de ovulação","US de mamas e axilas","US obstétrica","US morfológico 2º trimestre","US 3D ou 4D","US abdome total e superior","US aparelho urinário","US tireoide","US musculoesquelético","US parede abdominal"] },
  { id:"doppler", code:"02 · Avaliação de fluxos", title:"Doppler", text:"Recurso utilizado para avaliar o fluxo sanguíneo em vasos periféricos e no interior de órgãos.", image:"exame-doppler-colorido.webp", imageAlt:"Imagem de exame com Doppler colorido", label:"Principais modalidades", items:["Doppler das carótidas e vertebrais","Doppler venoso de membro inferior","Doppler arterial de membro inferior","Doppler venoso de membro superior","Doppler arterial de membro superior","Tireoide com Doppler","Testículo com Doppler","Musculoesquelético com Doppler","Doppler hepático","Doppler de artérias renais","Pélvica transvaginal com Doppler","Doppler obstétrico"] },
  { id:"mamografia", code:"03 · Saúde da mama", title:"Mamografia", text:"Tecnologia dedicada ao cuidado e à investigação por imagem da mama.", image:"exame-mamografia.jpg", imageAlt:"Imagem de exame de mamografia", label:"Modalidades disponíveis", items:["Mamografia Digital (DR)","Mamografia 3D (Tomossíntese)"] },
  { id:"procedimentos", code:"04 · Orientação por imagem", title:"Procedimentos Guiados por Imagem", text:"Punções, biópsias e marcações realizadas com orientação por imagem e acompanhamento médico especializado.", image:"exame-doppler.jpg", imageAlt:"Imagem diagnóstica utilizada em procedimentos guiados por imagem", label:"Procedimentos realizados", items:["Punção aspirativa por agulha fina (PAAF)","Core biópsia guiada por imagem","Punção mamária guiada por imagem","Marcação pré-cirúrgica com fio metálico","Marcação pré-cirúrgica por ROLL","Implante de clip de titânio"] },
];

export default function Exames(){return <><Header solid/><main><section className="inner-hero"><div className="container"><p className="eyebrow light">Exames e serviços</p><h1>Precisão para enxergar<br /><em>além da imagem.</em></h1><p>Conheça as principais categorias de exames e procedimentos realizados pela equipe Alpha.</p></div></section><section className="section"><div className="container exam-list">{groups.map(g=><article className="exam-group" id={g.id} key={g.id}><div className="exam-title"><span>{g.code}</span><figure className="exam-title-image"><img src={`/assets/${g.image}`} alt={g.imageAlt} width="750" height="750" /></figure><h2>{g.title}</h2><p>{g.text}</p></div><div className="exam-items"><h3>{g.label}</h3>{g.items.map(i=><span key={i}>{i}</span>)}</div></article>)}</div></section><section className="section cta-band"><div className="container cta-inner"><div><p className="eyebrow light">Precisa de orientação?</p><h2>Fale com nossa equipe.</h2><p>Confirme disponibilidade, preparo e cobertura do seu plano.</p></div><a className="button button-light" href="https://wa.me/552730606900" target="_blank" rel="noopener noreferrer">Solicitar agendamento ↗</a></div></section></main><Footer/></>}
