import { ContactForm, FAQ, Footer, Header, HeroImagingCanvas, ReviewsSection, TeamCarousel } from "./components";
import { Armchair, Heart, HeartHandshake, Radar, ScanLine, ShieldCheck, Stethoscope, UserRound, UsersRound } from "lucide-react";
import { getReviews } from "./reviews";

const plans = [["vale.jpg", "Vale"], ["arcelormittal.jpg", "ArcelorMittal"], ["unimed.jpg", "Unimed"], ["pasa.jpg", "PASA"], ["fusex.jpg", "Fusex"], ["cesan.jpg", "Cesan"], ["bluzz.jpg", "Bluzz Saúde"], ["banescaixa.jpg", "Banescaixa"]];

export default async function Home() {
  const reviews = await getReviews();
  return <><Header /><main>
    <section className="hero"><div className="hero-media" /><div className="hero-grid-layer" /><div className="hero-content container"><div className="hero-copy"><p className="eyebrow light">Alpha Imagem e Diagnóstico</p><h1><span className="hero-title-opening">Diagnóstico com </span><em>precisão</em><span className="hero-title-closing"><span className="hero-title-connector"> que</span><span className="hero-title-final"> transforma vidas</span></span></h1><p className="hero-lead">Tecnologia de última geração, equipe especializada e atendimento humanizado para os exames de imagem que você merece.</p><div className="hero-actions"><a className="button button-light hero-primary" href="https://wa.me/552730606900" target="_blank" rel="noopener noreferrer">Agendar exame <span>↗</span></a><a className="text-link light" href="/exames">Conhecer exames <span>→</span></a></div></div><HeroImagingCanvas /></div></section>
    <section className="trust-strip" aria-label="Diferenciais da Alpha"><div className="container trust-grid">
      <div className="trust-card"><i aria-hidden="true"><ScanLine strokeWidth={1.75} /></i><span>Tecnologia avançada</span></div>
      <div className="trust-card"><i aria-hidden="true"><UsersRound strokeWidth={1.75} /></i><span>Equipe especializada</span></div>
      <div className="trust-card"><i aria-hidden="true"><ShieldCheck strokeWidth={1.75} /></i><span>Diagnóstico seguro</span></div>
      <div className="trust-card"><i aria-hidden="true"><HeartHandshake strokeWidth={1.75} /></i><span>Atendimento humanizado</span></div>
    </div></section>
    <section className="section about technical-grid" id="sobre"><div className="container about-grid"><div className="about-image visual-frame"><img src="/assets/recepcao-clinica.jpg" width="998" height="473" alt="Recepção da Alpha Imagem e Diagnóstico" /><div className="image-note"><strong>Alpha</strong><span>Praia do Canto · Vitória</span></div></div><div className="about-copy"><p className="eyebrow">Sobre a Alpha</p><h2>Ciência e sensibilidade em uma mesma imagem.</h2><p>A Alpha é uma clínica de diagnóstico por imagem que reúne médicos com expertise e atualização constante, equipamentos de tecnologia avançada e atendimento personalizado.</p><p>Um ambiente pensado para que precisão técnica e acolhimento caminhem juntos, oferecendo segurança e atenção em cada exame.</p><a className="text-link" href="/equipe-estrutura">Conheça nossa história e estrutura <span>→</span></a></div></div></section>
    <section className="section services" id="exames"><div className="container"><div className="section-heading"><div><p className="eyebrow">Exames e serviços</p><h2>Tecnologia a serviço<br />do seu cuidado.</h2></div><p>Exames realizados por uma equipe especializada, com recursos avançados e atenção individual em cada etapa.</p></div><div className="service-grid">
      <a className="service-card service-ultra" href="/exames#ultrassonografia"><span className="service-number">01</span><div className="service-visual"><img src="/assets/exame-ultrassom.jpg" alt="Imagem de exame de ultrassonografia" width="750" height="750" /></div><div><p>Imagem em tempo real</p><h3>Ultrassonografia</h3><span>Modo B, 3D e 4D, Doppler colorido, Power Doppler e Doppler espectral.</span><div className="chips"><b>Saúde da mulher</b><b>Saúde do homem</b><b>Doppler</b></div></div><i className="round-arrow">↗</i></a>
      <a className="service-card service-mamo" href="/exames#mamografia"><span className="service-number">02</span><div className="service-visual"><img src="/assets/exame-mamografia.jpg" alt="Imagem de exame de mamografia" width="750" height="750" /></div><div><p>Cuidado e prevenção</p><h3>Mamografia</h3><span>Mamografia Digital (DR) e Mamografia 3D (Tomossíntese).</span><div className="chips"><b>Mamografia digital</b><b>Tomossíntese 3D</b></div></div><i className="round-arrow">↗</i></a>
      <a className="service-card service-procedure" href="/exames#procedimentos"><span className="service-number">03</span><div className="service-visual"><img src="/assets/exame-doppler.jpg" alt="Imagem diagnóstica utilizada em procedimento guiado" width="750" height="750" /></div><div><p>Precisão em cada etapa</p><h3>Procedimentos Guiados por Imagem</h3><span>Punções, biópsias e marcações realizadas com orientação por imagem.</span><div className="chips"><b>PAAF</b><b>Core biópsia</b><b>Marcações</b></div></div><i className="round-arrow">↗</i></a>
    </div><div className="center-action"><a className="button button-outline" href="/exames">Ver todos os exames <span>→</span></a></div></div></section>
    <section className="section distinction"><div className="ultrasound-rings" aria-hidden="true"><i /><i /><i /><i /><span /></div><div className="container"><div className="section-heading light-heading"><div><p className="eyebrow light">Por que escolher a Alpha</p><h2>Precisão em cada detalhe.<br /><em>Humanidade em cada encontro.</em></h2></div></div><div className="glass-grid">
      <article className="glass-card benefit-medical"><span className="glass-icon" aria-hidden="true"><Stethoscope strokeWidth={1.8} /></span><span className="glass-number">01</span><h3>Equipe médica especializada</h3><p>Profissionais experientes, com atualização constante e atuação dedicada em diagnóstico por imagem.</p></article>
      <article className="glass-card benefit-technology"><span className="glass-icon" aria-hidden="true"><Radar strokeWidth={1.8} /></span><span className="glass-number">02</span><h3>Tecnologia avançada</h3><p>Recursos de imagem modernos para apoiar exames detalhados e uma experiência mais segura.</p></article>
      <article className="glass-card benefit-care"><span className="glass-icon care-icon" aria-hidden="true"><UserRound className="care-user" strokeWidth={1.8} /><Heart className="care-heart" strokeWidth={1.8} /></span><span className="glass-number">03</span><h3>Atendimento personalizado</h3><p>Escuta, clareza e atenção individual desde o primeiro contato até a realização do exame.</p></article>
      <article className="glass-card benefit-comfort"><span className="glass-icon" aria-hidden="true"><Armchair strokeWidth={1.8} /></span><span className="glass-number">04</span><h3>Ambiente acolhedor</h3><p>Uma estrutura confortável, acessível e pensada para receber você com tranquilidade.</p></article>
    </div></div></section>
    <section className="section team-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Equipe médica</p><h2>Conhecimento que<br />inspira confiança.</h2><p className="team-intro">Uma equipe multidisciplinar que une experiência, atualização profissional e cuidado com cada paciente.</p><a className="text-link team-page-link" href="/equipe">Conheça toda a equipe <span>→</span></a></div></div><TeamCarousel /></div></section>
    <section className="section convenios" id="convenios"><div className="container"><div className="section-heading compact"><div><p className="eyebrow">Convênios</p><h2>Cuidado ao seu alcance.</h2></div><p>Consulte a disponibilidade do seu plano antes do agendamento.</p></div><div className="logo-grid">{plans.map(([src,name]) => <div className="plan-logo" key={name}><img src={`/assets/${src}`} alt={`Convênio ${name}`} loading="lazy" /></div>)}</div><p className="plan-note">A cobertura pode variar conforme o produto contratado. Confirme o atendimento do seu plano específico com nossa equipe.</p></div></section>
    <section className="section cta-band"><div className="container cta-inner"><div><p className="eyebrow light">Seu cuidado começa aqui</p><h2>Pronto para agendar seu exame?</h2><p>Fale com nossa equipe e receba as orientações necessárias.</p></div><div className="cta-actions"><a className="button button-light" href="https://wa.me/552730606900" target="_blank" rel="noopener noreferrer">Agendar pelo WhatsApp <span>↗</span></a><a href="tel:+552730606900">ou ligue <strong>(27) 3060-6900</strong></a></div></div></section>
    <section className="section faq-section"><div className="container faq-grid"><div><p className="eyebrow">Dúvidas frequentes</p><h2>Informação clara também faz parte do cuidado.</h2><p>Reunimos algumas das dúvidas mais comuns para você chegar ao seu exame com mais informação e tranquilidade.</p></div><FAQ /></div></section>
    <ReviewsSection {...reviews} />
    <section className="section contact" id="contato"><div className="container contact-grid"><div className="contact-copy"><p className="eyebrow light">Contato e localização</p><h2>Estamos no coração da Praia do Canto.</h2><div className="contact-list"><div><small>Endereço</small><p>Rua Desembargador Sampaio, 177<br />Praia do Canto, Vitória - ES</p><a href="https://maps.google.com/?q=Rua+Desembargador+Sampaio+177+Vitória+ES" target="_blank" rel="noopener noreferrer">Como chegar ↗</a></div><div><small>Horário</small><p>Segunda a sexta<br />7h às 18h</p></div><div><small>Contato</small><p>(27) 3060-6900<br />atendimento@alphadiagnostico.com</p></div></div></div><ContactForm /></div></section>
  </main><Footer /><a className="whatsapp-float" href="https://wa.me/552730606900" target="_blank" rel="noopener noreferrer" aria-label="Falar com a Alpha pelo WhatsApp"><img src="/assets/whatsapp-button.png" alt="" width="554" height="554" aria-hidden="true" /></a></>;
}
