export const team = [
  { name: "Dr. Camilo Frizzera Borges", role: "Médico ultrassonografista", image: "/assets/dr-camilo-frizzera.jpg", summary: "Especialista em ultrassonografia geral e em ginecologia e obstetrícia.", details: ["Especialista em Ultrassonografia Geral pelo Colégio Brasileiro de Radiologia.", "Especialista em Ultrassonografia com área de atuação em Ginecologia e Obstetrícia pela FEBRASGO/CBR.", "Residência médica em Ginecologia e Obstetrícia pela Maternidade Octaviano Neves."] },
  { name: "Dra. Vanessa Bastos Bandeira", role: "Médica ultrassonografista", image: "/assets/dra-vanessa.jpg", summary: "Atuação exclusiva em ultrassonografia geral, ginecologia e obstetrícia.", details: ["Título de especialista em Diagnóstico por Imagem, com atuação exclusiva em Ultrassonografia Geral — RQE 5727.", "Certificado de atuação em Ultrassonografia em Ginecologia e Obstetrícia — RQE 4985.", "Competence in Ultrasound Examination at 11–14 weeks pela The Fetal Medicine Foundation.", "Residência Médica em Ginecologia e Obstetrícia pelo Hospital do Servidor Público Municipal de São Paulo e TEGO — RQE 4322."] },
  { name: "Dr. Luiz Sérgio P. Grillo Jr.", role: "Médico radiologista e radiologista intervencionista", image: "/assets/dr-luiz.jpg", summary: "Especialista em radiologia, diagnóstico por imagem e radiologia intervencionista.", details: ["Especialista em Radiologia e Diagnóstico por Imagem pelo Hospital das Forças Armadas e membro titular do CBR — RQE 11.434.", "Especialista em Radiologia Intervencionista e Angiorradiologia, membro titular da SOBRICE e do CBR — RQE 7120.", "MBA em Gestão de Serviços de Saúde pela FGV."] },
  { name: "Dra. Cláudia T. Salviato Mameri", role: "Imaginologista de mama", image: "/assets/dra-claudia.jpg", summary: "Mastologista, pós-graduada em Radiologia Mamária e pesquisadora de doenças mamárias da UFES.", details: ["Mastologista e pós-graduada em Radiologia Mamária pela UNIFESP.", "Fellow na Universidade de São Francisco, Califórnia, e na Universidade de Bonn, Alemanha.", "Presidente da Sociedade Brasileira de Mastologia por dois triênios.", "Pesquisadora de doenças mamárias da UFES."] },
  { name: "Dra. Janine Machado", role: "Imaginologista de mama", image: "/assets/dr-janine.jpg", summary: "Mastologista com área de atuação em mamografia e mestrado em ginecologia e mastologia.", details: ["Graduada em Medicina pela Universidade Federal do Espírito Santo.", "Residência Médica em Ginecologia e Obstetrícia e em Mastologia pelo HUCAM/UFES.", "Certificado de Área de Atuação em Mamografia pelo CBR, FEBRASGO e SBM.", "Mestrado em Ginecologia e Mastologia pela UNIFESP e coordenação da Residência Médica de Mastologia do HUCAM/UFES."] },
  { name: "Dra. Samara Riguete Zacchi", role: "Médica radiologista e médica nuclear", image: "/assets/dra-samara.jpg", summary: "Especialista em radiologia, diagnóstico por imagem e medicina nuclear.", details: ["Residência em Radiologia e Diagnóstico por Imagem pela UFES, com título de especialista pelo CBR — RQE 10.103.", "Residência em Medicina Nuclear pelo HC-FMUSP, com título de especialista pela Sociedade Brasileira de Medicina Nuclear — RQE 10.102."] },
  { name: "Dra. Laís dos Santos Gueiros", role: "Imaginologista de mama", image: "/assets/dra-lais.jpg", summary: "Mastologista com área de atuação em mamografia e ultrassonografia mamária.", details: ["Graduada em Medicina pela EMESCAM.", "Residência Médica em Cirurgia Geral pela Santa Casa de Misericórdia de Vitória e em Mastologia pelo HUCAM/UFES.", "Certificado de Área de Atuação em Mamografia pelo CBR, FEBRASGO e SBM.", "Especialização em Ultrassonografia Mamária, Prática Intensiva Mamária e Tópicos Avançados pela FATESA."] },
];
